name: Update all files

on:
  push:
    paths:
      - 'rules/rules_direct'
      - 'rules/rules_proxy'

jobs:
  execute_script:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute deploy.sh
        run: |
          cd .github
          chmod +x deploy.sh
          ./deploy.sh

      - name: Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git reset .github/
          git restore .github/deploy.sh
          git clean -df
          git commit -m "Update files"
          git push
